"use client";
import "@mantine/core/styles.css";
import "./global.css";
import "@mantine/carousel/styles.css";
import {
  ColorSchemeScript,
  createTheme,
  MantineProvider,
  Title,
  Box,
} from "@mantine/core";
import { Grid } from "@mantine/core";
import { Navbar } from "@/components/NavBar";
import Featured from "@/components/Featured";
import { Heading } from "@/components/Heading";
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme = createTheme({});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <Grid>
            <Grid.Col span={{ base: 12, xs: 2.4 }}>
              <Navbar />
            </Grid.Col>

            <Grid.Col span={{ base: 12, xs: 9.6 }}>
              <Heading />
              <Grid>
                <Grid.Col span={{ base: 12, xs: 9 }}>{children}</Grid.Col>
                <Grid.Col span={{ base: 12, xs: 3 }}>
                  <Featured />
                </Grid.Col>
              </Grid>
            </Grid.Col>
          </Grid>
        </MantineProvider>
      </body>
    </html>
  );
}
