import Details from "@/components/Details";
import React from "react";

export default function page({ params }) {
  const data1 = {
    pros: [
      "Web-based tool",
      "Image upload support",
      "Useful for social media",
      "Ideal for blog content",
      "Simple and straightforward",
      "Saves time on captioning",
      "Useful for businesses",
      "Functional for organizations",
      "Practical tool",
      "Built with create-react-app",
      "Offers convenient efficiency",
      "JavaScript enabled features",
    ],
    cons: [
      "Web-based only",
      "No mobile app",
      "No batch processing",
      "No API",
      "No integration with social media",
      "No customizable captions",
      "No offline usage",
      "No caption editing",
      "Potential misinterpretation of images",
      "Risk of inappropriate captions",
    ],

    questions: [
      {
        question: "What is ImageToCaption designed to do?",
        answer:
          "ImageToCaption is designed to generate captions for uploaded images using AI algorithms.",
      },
      {
        question: "Where can one access ImageToCaption?",
        answer:
          "ImageToCaption is accessible through its website, imagetocaption.ai.",
      },
      {
        question: "What is required to generate captions using ImageToCaption?",
        answer:
          "Users need to upload an image to ImageToCaption to generate a caption.",
      },
      {
        question: "What type of users can use ImageToCaption?",
        answer:
          "ImageToCaption can be used by any individuals, businesses, or organizations who need to generate captions for images.",
      },
      {
        question: "How can the captions generated by ImageToCaption be used?",
        answer:
          "The captions generated by ImageToCaption can be used in social media posts, blog articles, and other types of content.",
      },
      {
        question:
          "What are the steps to generate a caption using ImageToCaption?",
        answer:
          "The steps to generate a caption using ImageToCaption are: upload an image to the platform and the AI algorithms will analyze the image and generate a relevant caption. The generated caption can then be copied and used as required.",
      },
      {
        question:
          "Does ImageToCaption require any specific browser configurations?",
        answer: "IDK",
      },
      {
        question: "Can ImageToCaption analyze any type of image?",
        answer: "IDK",
      },
      {
        question:
          "Does ImageToCaption offer assistance or support for the users?",
        answer: "IDK",
      },
      {
        question:
          "How fast does ImageToCaption generate captions for an image?",
        answer:
          "The precise speed at which ImageToCaption generates captions was not specified on their website, but the tool is designed to quickly analyze images and generate captions.",
      },
      {
        question: "Is ImageToCaption accessible on mobile devices?",
        answer: "IDK",
      },
      {
        question: "Does ImageToCaption require any software installation?",
        answer:
          "No software installation is required to use ImageToCaption. It is a web-based tool available through its website.",
      },
      {
        question: "What type of AI algorithms does ImageToCaption utilize?",
        answer:
          "ImageToCaption uses AI algorithms to analyze images and generate captions. The specific type of AI algorithms used was not mentioned on their website.",
      },
      {
        question: "How accurate are the captions generated by ImageToCaption?",
        answer:
          "The accuracy of the captions generated by ImageToCaption was not specified on their website.",
      },
      {
        question: "Can I use ImageToCaption for my business?",
        answer:
          "Yes, businesses can use ImageToCaption for generating captions for their images.",
      },
    ],

    alternates: [
      {
        title: "Adspire",
        description: "Ads",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496574.png?f=webp&w=256",
        price: "Free + from $9.99",
      },
      {
        title: "Assistena",
        description: "Academic assistant",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496575.png?f=webp&w=256",
        price: "Free",
      },
      {
        title: "Assistesna",
        description: "Academic assistant",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496576.png?f=webp&w=256",
        price: "Free",
      },
      {
        title: "Assistena",
        description: "Academic assistant",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496577.png?f=webp&w=256",
        price: "Free",
      },
      {
        title: "Assistena",
        description: "Academic assistant",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496578.png?f=webp&w=256",
        price: "Free",
      },
    ],
    reviews: [
      {
        user: "John Doe",
        rating: 5,
        date: "2021-01-01",
        review:
          "Adspire is an amazing tool that has helped me create high-quality ads for my business. I highly recommend it to anyone looking to improve their marketing efforts.",
      },
      {
        user: "Jane Smith",
        rating: 4,
        date: "2021-01-02",
        review:
          "I've been using Adspire for a few months now and I'm very impressed with the results. It's easy to use and has helped me save time and money on my marketing campaigns.",
      },
      {
        user: "Alice Johnson",
        rating: 3,
        date: "2021-01-03",
        review:
          "Adspire is a good tool for creating ads, but it could use some improvements. I've had some issues with the interface and the ad templates.",
      },
    ],
    title: "Adspire",
    description: "AI Ad Generator",
    logo: "https://cdn.iconscout.com/icon/premium/png-512-thumb/cdn-9177118-7494359.png?f=webp&w=256",
    rating: 3,
    overview:
      "Adspire is an AI-powered ad generator that helps you create high-quality ads for your business. lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum, temporibus dolor! Ut reprehenderit neque quam beatae voluptate sint explicabo nostrum debitis. Sed reiciendis soluta dolorem dignissimos facilis dolore, eius illum? lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum, temporibus dolor! Ut reprehenderit neque quam beatae voluptate sint explicabo nostrum debitis. Sed reiciendis soluta dolorem dignissimos facilis dolore, eius illum? lorem ipsum ",
    screenshots: [
      "https://www.cssdesignawards.com/cdasites/2024/202405/20240528090646.jpg",
      "https://res.cloudinary.com/learncomputeracademy/images/w_1011,h_569,c_scale/f_webp/v1690401427/awwwards-screenshot/awwwards-screenshot.jpg?_i=AA",
    ],
  };

  const data2 = {
    pros: [
      "Mobile application",
      "Supports multiple file formats",
      "Ideal for personal use",
      "Great for photo editing",
      "User-friendly interface",
      "Automated editing options",
      "Perfect for photographers",
      "Useful for design agencies",
      "Practical and efficient",
      "Built with Vue.js",
      "Enhances productivity",
      "Advanced editing features",
    ],
    cons: [
      "Requires internet connection",
      "No desktop application",
      "Limited free version",
      "No API",
      "No integration with cloud storage",
      "Limited editing options in free version",
      "No offline usage",
      "No batch editing",
      "Risk of over-editing",
      "Limited file storage",
    ],
    questions: [
      {
        question: "What is PhotoMaster designed to do?",
        answer:
          "PhotoMaster is designed to provide automated editing options for uploaded photos.",
      },
      {
        question: "Where can one access PhotoMaster?",
        answer: "PhotoMaster is accessible through its mobile application.",
      },
      {
        question: "What is required to edit photos using PhotoMaster?",
        answer: "Users need to upload a photo to PhotoMaster to start editing.",
      },
      {
        question: "What type of users can use PhotoMaster?",
        answer:
          "PhotoMaster can be used by any individuals, photographers, or design agencies who need to edit photos.",
      },
      {
        question: "How can the photos edited by PhotoMaster be used?",
        answer:
          "The photos edited by PhotoMaster can be used in social media posts, websites, and other types of content.",
      },
      {
        question: "What are the steps to edit a photo using PhotoMaster?",
        answer:
          "The steps to edit a photo using PhotoMaster are: upload a photo to the app, choose an editing option, and save the edited photo.",
      },
      // ... more questions
    ],
    alternates: [
      {
        title: "PhotoGenius",
        description: "Photo editing tool",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496574.png?f=webp&w=256",
        price: "Free + from $14.99",
      },
      // ... more alternates
    ],
    reviews: [
      {
        user: "Robert Brown",
        rating: 4,
        date: "2021-01-01",
        review:
          "PhotoMaster is a great tool for editing photos. It's easy to use and offers a variety of editing options.",
      },
    ],
    title: "PhotoMaster",
    description: "Automated Photo Editing Tool",
    logo: "https://cdn.iconscout.com/icon/premium/png-512-thumb/cdn-9177118-7494359.png?f=webp&w=256",
    rating: 4,
    overview:
      "PhotoMaster is an automated photo editing tool that helps you create high-quality photos for your personal or professional use. It's built with Vue.js and offers a variety of advanced editing features.",
    screenshots: [
      "https://www.cssdesignawards.com/cdasites/2024/202405/20240528090646.jpg",
      "https://res.cloudinary.com/learncomputeracademy/images/w_1011,h_569,c_scale/f_webp/v1690401427/awwwards-screenshot/awwwards-screenshot.jpg?_i=AA",
    ],
  };

  const data3 = {
    pros: [
      "Web application",
      "Supports multiple document formats",
      "Ideal for business use",
      "Great for document editing",
      "User-friendly interface",
      "Automated editing options",
      "Perfect for writers",
      "Useful for publishing agencies",
      "Practical and efficient",
      "Built with React.js",
      "Enhances productivity",
      "Advanced editing features",
    ],
    cons: [
      "Requires internet connection",
      "No mobile application",
      "Limited free version",
      "No API",
      "No integration with cloud storage",
      "Limited editing options in free version",
      "No offline usage",
      "No batch editing",
      "Risk of over-editing",
      "Limited file storage",
    ],
    questions: [
      {
        question: "What is DocMaster designed to do?",
        answer:
          "DocMaster is designed to provide automated editing options for uploaded documents.",
      },
      {
        question: "Where can one access DocMaster?",
        answer: "DocMaster is accessible through its web application.",
      },
      // ... more questions
    ],
    alternates: [
      {
        title: "DocGenius",
        description: "Document editing tool",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496574.png?f=webp&w=256",
        price: "Free + from $19.99",
      },
      // ... more alternates
    ],
    reviews: [
      {
        user: "Alice Smith",
        rating: 5,
        date: "2021-02-01",
        review:
          "DocMaster is a great tool for editing documents. It's easy to use and offers a variety of editing options.",
      },
      // ... more reviews
    ],
    title: "DocMaster",
    description: "Automated Document Editing Tool",
    logo: "https://cdn.iconscout.com/icon/premium/png-512-thumb/cdn-9177118-7494260.png?f=webp&w=256",
    rating: 5,
    overview:
      "DocMaster is an automated document editing tool that helps you create high-quality documents for your personal or professional use. It's built with React.js and offers a variety of advanced editing features.",
    screenshots: [
      "https://www.cssdesignawards.com/cdasites/2024/202405/20240528090646.jpg",
      "https://res.cloudinary.com/learncomputeracademy/images/w_1011,h_569,c_scale/f_webp/v1690401427/awwwards-screenshot/awwwards-screenshot.jpg?_i=AA",
    ],
  };

  const data4 = {
    pros: [
      "Desktop application",
      "Supports multiple video formats",
      "Ideal for professional use",
      "Great for video editing",
      "User-friendly interface",
      "Automated editing options",
      "Perfect for videographers",
      "Useful for production agencies",
      "Practical and efficient",
      "Built with Electron.js",
      "Enhances productivity",
      "Advanced editing features",
    ],
    cons: [
      "Requires software installation",
      "No mobile application",
      "Limited free version",
      "No API",
      "No integration with cloud storage",
      "Limited editing options in free version",
      "No offline usage",
      "No batch editing",
      "Risk of over-editing",
      "Limited file storage",
    ],
    questions: [
      {
        question: "What is VideoMaster designed to do?",
        answer:
          "VideoMaster is designed to provide automated editing options for uploaded videos.",
      },
      {
        question: "Where can one access VideoMaster?",
        answer: "VideoMaster is accessible through its desktop application.",
      },
      // ... more questions
    ],
    alternates: [
      {
        title: "VideoGenius",
        description: "Video editing tool",
        logo: "https://cdn.iconscout.com/icon/free/png-512/free-cdn-1758346-1496574.png?f=webp&w=256",
        price: "Free + from $24.99",
      },
      // ... more alternates
    ],
    reviews: [
      {
        user: "John Doe",
        rating: 4.5,
        date: "2021-03-01",
        review:
          "VideoMaster is a great tool for editing videos. It's easy to use and offers a variety of editing options.",
      },
      // ... more reviews
    ],
    title: "VideoMaster",
    description: "Automated Video Editing Tool",
    logo: "https://cdn.iconscout.com/icon/premium/png-512-thumb/cdn-9177118-7494349.png?f=webp&w=256",
    rating: 4.5,
    overview:
      "VideoMaster is an automated video editing tool that helps you create high-quality videos for your personal or professional use. It's built with Electron.js and offers a variety of advanced editing features.",
    screenshots: [
      "https://www.cssdesignawards.com/cdasites/2024/202405/20240528090646.jpg",
      "https://res.cloudinary.com/learncomputeracademy/images/w_1011,h_569,c_scale/f_webp/v1690401427/awwwards-screenshot/awwwards-screenshot.jpg?_i=AA",
    ],
  };

  const dict = {
    adspire: data1,
    assistena: data2,
    webr: data3,
    andr: data4,
  };
  return <Details data={dict[params.id]} />;
}
